# Generated by Django 5.0.7 on 2025-01-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('address', models.TextField()),
                ('salary', models.IntegerField()),
                ('joined_date', models.DateField()),
            ],
        ),
    ]
