# Generated by Django 5.0.7 on 2025-01-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='staff_id',
            field=models.CharField(max_length=20),
        ),
    ]
