# Generated by Django 5.0.7 on 2025-01-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_staffs_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
