# Generated by Django 5.0.7 on 2025-01-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_staffs_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
