# Generated by Django 5.0.7 on 2025-01-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_attendance_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='staff_img',
            field=models.ImageField(blank=True, null=True, upload_to='upload/staffs'),
        ),
    ]
