# Generated by Django 5.0.7 on 2025-04-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_staffs_staff_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='staff_img',
        ),
        migrations.CreateModel(
            name='StaffImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/staffs/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.staffs')),
            ],
        ),
    ]
